name: Noir Test

on: [push, pull_request]

jobs:
    test:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Nargo
              uses: noir-lang/noirup@v0.1.3
              with:
                  toolchain: 1.0.0-beta.1
            - name: Build circuits
              run: |
                  cd circuits
                  sh ./scripts/generate-proof-artifacts.sh keccak
            - name: Test Noir
              run: |
                  cargo test --all-features
